import 'package:flutter/material.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:intl/intl.dart';

class ShippingProvider extends ChangeNotifier {
  late Box dataBox;

    final precioEnvioCtrl = TextEditingController();
      final pesoEnvioCtrl = TextEditingController();
        final proxyCostoCtrl = TextEditingController(text: "5.0");

          String monedaProxy = 'USD';
            String origenEnvio = 'Japón';
              String destinoEnvio = 'Brasil';
                String monedaOrigenEnvio = 'USD';
                  String monedaDestinoEnvio = 'USD';
                    String desgloseEnvio = "Ingresa datos para calcular...";
                      double totalEnvio = 0.0;
                        List<Map<String, dynamic>> cotizaciones = [];

                          Map<String, double> _tasasCambio = {};
                            bool _applySpread = false;
                              double _spreadPercent = 0.0;

                                final Map<String, Map<String, dynamic>> taxRules = {
                                    'Brasil': { 'limit': 50.0, 'under_limit_tax': 0.20, 'over_limit_tax': 0.60, 'state_tax_icms': 0.17 },
                                        'Perú': { 'limit': 200.0, 'under_limit_tax': 0.0, 'over_limit_tax': 0.22, 'state_tax_icms': 0.0 },
                                            'México': { 'limit': 50.0, 'under_limit_tax': 0.0, 'over_limit_tax': 0.19, 'state_tax_icms': 0.0 },
                                                'EE.UU.': { 'limit': 800.0, 'under_limit_tax': 0.0, 'over_limit_tax': 0.10, 'state_tax_icms': 0.0 },
                                                    'Europa': { 'limit': 150.0, 'under_limit_tax': 0.21, 'over_limit_tax': 0.235, 'state_tax_icms': 0.0 },
                                                        'Japón': { 'limit': 0.0, 'under_limit_tax': 0.10, 'over_limit_tax': 0.10, 'state_tax_icms': 0.0 },
                                                            'Venezuela': { 'limit': 0.0, 'under_limit_tax': 0.30, 'over_limit_tax': 0.30, 'state_tax_icms': 0.0 },
                                                              };

                                                                ShippingProvider() {
                                                                    dataBox = Hive.box('dataBox');
                                                                        _cargarDatosLocales();
                                                                          }

                                                                            void _cargarDatosLocales() {
                                                                                proxyCostoCtrl.text = dataBox.get('proxyCosto', defaultValue: "5.0");
                                                                                    monedaProxy = dataBox.get('monedaProxy', defaultValue: "USD");
                                                                                        destinoEnvio = dataBox.get('destinoEnvio', defaultValue: "Brasil");
                                                                                            monedaDestinoEnvio = dataBox.get('monedaDestinoEnvio', defaultValue: "USD");
                                                                                                var cot = dataBox.get('cotizaciones');
                                                                                                    if (cot != null) cotizaciones = List<Map<String, dynamic>>.from(cot.map((e) => Map<String, dynamic>.from(e)));
                                                                                                      }

                                                                                                        void _guardarDatos() {
                                                                                                            dataBox.putAll({
                                                                                                                  'proxyCosto': proxyCostoCtrl.text,
                                                                                                                        'monedaProxy': monedaProxy,
                                                                                                                              'destinoEnvio': destinoEnvio,
                                                                                                                                    'monedaDestinoEnvio': monedaDestinoEnvio,
                                                                                                                                          'cotizaciones': cotizaciones
                                                                                                                                              });
                                                                                                                                                }

                                                                                                                                                  void updateDependencies(Map<String, double> tasas, bool applySpread, double spreadPercent) {
                                                                                                                                                      _tasasCambio = tasas;
                                                                                                                                                          _applySpread = applySpread;
                                                                                                                                                              _spreadPercent = spreadPercent;
                                                                                                                                                                  calcularEnvio();
                                                                                                                                                                    }

                                                                                                                                                                      void updateEnvioParams({String? mProxy, String? origen, String? destino, String? mOrigen, String? mDestino}) {
                                                                                                                                                                          if (mProxy != null) monedaProxy = mProxy;
                                                                                                                                                                              if (origen != null) origenEnvio = origen;
                                                                                                                                                                                  if (destino != null) destinoEnvio = destino;
                                                                                                                                                                                      if (mOrigen != null) monedaOrigenEnvio = mOrigen;
                                                                                                                                                                                          if (mDestino != null) monedaDestinoEnvio = mDestino;
                                                                                                                                                                                              calcularEnvio();
                                                                                                                                                                                                }

                                                                                                                                                                                                  void calcularEnvio() {
                                                                                                                                                                                                      if (_tasasCambio.isEmpty) return;
                                                                                                                                                                                                          double precioOrigen = double.tryParse(precioEnvioCtrl.text) ?? 0.0;
                                                                                                                                                                                                              double pesoKg = double.tryParse(pesoEnvioCtrl.text) ?? 0.0;
                                                                                                                                                                                                                  double costoProxyInput = double.tryParse(proxyCostoCtrl.text) ?? 0.0;

                                                                                                                                                                                                                      if (precioOrigen == 0 && pesoKg == 0) {
                                                                                                                                                                                                                            desgloseEnvio = "Ingresa datos para calcular..."; totalEnvio = 0.0;
                                                                                                                                                                                                                                  notifyListeners(); return;
                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                          double precioUsd = precioOrigen / (_tasasCambio[monedaOrigenEnvio] ?? 1.0);
                                                                                                                                                                                                                                              double proxyFeeUsd = costoProxyInput / (_tasasCambio[monedaProxy] ?? 1.0);
                                                                                                                                                                                                                                                  double costoEnvioUsd = 0.0;
                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                          if (origenEnvio == 'Nacional') costoEnvioUsd = 4.0 + (pesoKg * 2.5);
                                                                                                                                                                                                                                                              else if (origenEnvio == 'China') costoEnvioUsd = 3.0 + (pesoKg * 15.0);
                                                                                                                                                                                                                                                                  else if (origenEnvio == 'EE.UU.') costoEnvioUsd = 12.0 + (pesoKg * 9.0);
                                                                                                                                                                                                                                                                      else if (origenEnvio == 'Japón') costoEnvioUsd = 15.0 + (pesoKg * 22.0);
                                                                                                                                                                                                                                                                          else if (origenEnvio == 'Europa') costoEnvioUsd = 14.0 + (pesoKg * 18.0);

                                                                                                                                                                                                                                                                              double baseCif = precioUsd + costoEnvioUsd + proxyFeeUsd;
                                                                                                                                                                                                                                                                                  var rule = taxRules[destinoEnvio] ?? { 'limit': 0.0, 'under_limit_tax': 0.30, 'over_limit_tax': 0.30, 'state_tax_icms': 0.0 };
                                                                                                                                                                                                                                                                                      double baseTaxRate = precioUsd <= rule['limit'] ? rule['under_limit_tax'] : rule['over_limit_tax'];
                                                                                                                                                                                                                                                                                          double federalTaxUsd = baseCif * baseTaxRate;
                                                                                                                                                                                                                                                                                              double baseWithFederal = baseCif + federalTaxUsd;
                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                      double impuestoUsd = rule['state_tax_icms'] > 0 ? (baseWithFederal / (1 - rule['state_tax_icms'])) - baseCif : federalTaxUsd;
                                                                                                                                                                                                                                                                                                          double totalUsd = baseCif + impuestoUsd;
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                  final numFormat = NumberFormat('#,##0.00', 'en_US');
                                                                                                                                                                                                                                                                                                                      double totalBaseFinal = totalUsd * (_tasasCambio[monedaDestinoEnvio] ?? 1.0);
                                                                                                                                                                                                                                                                                                                          totalEnvio = (_applySpread && _spreadPercent > 0) ? totalBaseFinal * (1 + (_spreadPercent / 100)) : totalBaseFinal;
                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                  desgloseEnvio = "Valor (USD): \$${numFormat.format(precioUsd)}\nFlete: \$${numFormat.format(costoEnvioUsd)}"
                                                                                                                                                                                                                                                                                                                                          "${proxyFeeUsd > 0 ? ' | Proxy: \$${numFormat.format(proxyFeeUsd)}' : ''}"
                                                                                                                                                                                                                                                                                                                                                  "${impuestoUsd > 0 ? ' | Aduana: \$${numFormat.format(impuestoUsd)}' : ''}"
                                                                                                                                                                                                                                                                                                                                                          "${_applySpread && _spreadPercent > 0 ? '\n+ Comisión Bancaria: $_spreadPercent%' : ''}";
                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                  _guardarDatos();
                                                                                                                                                                                                                                                                                                                                                                      notifyListeners();
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                          void guardarCotizacion() {
                                                                                                                                                                                                                                                                                                                                                                              if (totalEnvio <= 0) return;
                                                                                                                                                                                                                                                                                                                                                                                  cotizaciones.insert(0, {
                                                                                                                                                                                                                                                                                                                                                                                        'id': DateTime.now().millisecondsSinceEpoch.toString(), 
                                                                                                                                                                                                                                                                                                                                                                                              'fecha': DateFormat('dd/MM HH:mm').format(DateTime.now()),
                                                                                                                                                                                                                                                                                                                                                                                                    'origen': origenEnvio, 'destino': destinoEnvio, 
                                                                                                                                                                                                                                                                                                                                                                                                          'peso': pesoEnvioCtrl.text.isEmpty ? "0" : pesoEnvioCtrl.text,
                                                                                                                                                                                                                                                                                                                                                                                                                'total': totalEnvio, 'moneda': monedaDestinoEnvio
                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                        _guardarDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                            notifyListeners();
                                                                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                                                                                void eliminarCotizacion(String id) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    cotizaciones.removeWhere((e) => e['id'] == id);
                                                                                                                                                                                                                                                                                                                                                                                                                                        _guardarDatos();
                                                                                                                                                                                                                                                                                                                                                                                                                                            notifyListeners();
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                              